### ISSUE TITLE
There is no rtklib_ros_bridge_sample.sh  file.

### ISSUE THREAD

**Issue by zang09** [MapIV/rtklib_ros_bridge#2]

**Comment by rsasaki0109** [comment]
@zang09 
For GNSS SPP, use rtklib_ros_bridge_single.sh/conf, and for RTK, use rtklib_ros_bridge_meijo_rtk.sh/conf.

sh
https://github.com/MapIV/RTKLIB/tree/rtklib_ros_bridge
conf
https://github.com/MapIV/RTKLIB/tree/rtklib_ros_bridge/app/rtkrcv/conf
